# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /app
RUN mkdir ./frontend
# Copy all files from host frontend directory to container frontend directory
COPY frontend ./frontend
WORKDIR /app/frontend
RUN npm install
RUN npm run build

# Build step #2: build the API with the client as static files
FROM python:3.11.2
WORKDIR /app
COPY --from=build-step /app/frontend/build ./frontend/build

RUN mkdir ./backend
# Copy all files from host backend directory to container backend directory
COPY backend ./backend
RUN pip install --upgrade pip && pip install -r ./backend/requirements.txt
ENV ENV production

EXPOSE 5000
WORKDIR /app/backend
CMD ["gunicorn", "-b", ":5000", "app:app"]
