version: "3.9"
services:
  chartgpt:
    env_file: config/.env
    build:
      context: .
      dockerfile: Dockerfile.combo
    image: chartgpt-combo
    ports:
      - "5000:5000"
    environment:
      - ENV=prod
