version: "3.9"
services:
  chartgpt:
    env_file: ../config/.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: chartgpt-dev
    ports:
      - "5000:5000"
      - "3000:3000"
    environment:
      - ENV=dev
    volumes:
      - ..:/app
